spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      partitionCount: 2
      replicaCount: 1
  main:
    banner-mode: off
springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /api/v1/docs-ui.html

