spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      partitionCount: 2
      replicaCount: 1
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudplatform
    username: core_user
    password: sd$2sq1K52Fa
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /api/v1/docs-ui.html

